// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhEroJG-YpNgBkvsfC3_eDvSZZSRh4DB4',
    appId: '1:260450139061:web:d35fabb82e22df912937fc',
    messagingSenderId: '260450139061',
    projectId: 'noobz-7f237',
    authDomain: 'noobz-7f237.firebaseapp.com',
    storageBucket: 'noobz-7f237.appspot.com',
    measurementId: 'G-K41TGKJ529',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa5KtyCETV6KrV6y1C2Ci_W5UN9OojN7s',
    appId: '1:260450139061:android:f61cc3f797cf91672937fc',
    messagingSenderId: '260450139061',
    projectId: 'noobz-7f237',
    storageBucket: 'noobz-7f237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgz9AzFdGyNW8dfDjKDw2ieE7YcNpR6g4',
    appId: '1:260450139061:ios:9cfbb5ec95ec09952937fc',
    messagingSenderId: '260450139061',
    projectId: 'noobz-7f237',
    storageBucket: 'noobz-7f237.appspot.com',
    iosBundleId: 'com.tritec.noobz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgz9AzFdGyNW8dfDjKDw2ieE7YcNpR6g4',
    appId: '1:260450139061:ios:27f0dda677c3fe4c2937fc',
    messagingSenderId: '260450139061',
    projectId: 'noobz-7f237',
    storageBucket: 'noobz-7f237.appspot.com',
    iosBundleId: 'com.tritec.noobz.RunnerTests',
  );
}
