// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0AjzP7aJRzWLVy2rLfpDcP2lMnhES-Cc',
    appId: '1:529370155955:web:656775527353b87370d9c6',
    messagingSenderId: '529370155955',
    projectId: 'movement-app-68bbc',
    authDomain: 'movement-app-68bbc.firebaseapp.com',
    storageBucket: 'movement-app-68bbc.appspot.com',
    measurementId: 'G-WW0ZL65MMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqmIBscikhlD4RoYDHCAFZ4sbT4a0omuo',
    appId: '1:529370155955:android:84f394b42f5266dc70d9c6',
    messagingSenderId: '529370155955',
    projectId: 'movement-app-68bbc',
    storageBucket: 'movement-app-68bbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskNi_SHejNoAKOncQS9LVwi0NVDbLerU',
    appId: '1:529370155955:ios:62f9f4f7d3af4dc270d9c6',
    messagingSenderId: '529370155955',
    projectId: 'movement-app-68bbc',
    storageBucket: 'movement-app-68bbc.appspot.com',
    iosBundleId: 'se.movementapp.movementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDskNi_SHejNoAKOncQS9LVwi0NVDbLerU',
    appId: '1:529370155955:ios:42422cfde0b0207370d9c6',
    messagingSenderId: '529370155955',
    projectId: 'movement-app-68bbc',
    storageBucket: 'movement-app-68bbc.appspot.com',
    iosBundleId: 'com.example.academyApp.RunnerTests',
  );
}
